export const FETCH_TITLES_LIST_PENDING = 'FETCH_TITLES_LIST_PENDING';
export const FETCH_TITLES_LIST_SUCCESS = 'FETCH_TITLES_LIST_SUCCESS';
export const FETCH_TITLES_LIST_ERROR = 'FETCH_TITLES_LIST_ERROR';
