export const SEARCH_BOOK_BY_ID_PENDING = 'SEARCH_BOOK_BY_ID_PENDING';
export const SEARCH_BOOK_BY_ID_SUCCESS = 'SEARCH_BOOK_BY_ID_SUCCESS';
export const SEARCH_BOOK_BY_ID_ERROR = 'SEARCH_BOOK_BY_ID_ERROR';
